# Generated by Django 4.2.5 on 2024-04-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuloBandeja',
            new_name='FrontendModule',
        ),
    ]
