# Generated by Django 4.2.5 on 2024-04-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_management', '0002_rename_modulobandeja_frontendmodule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statework',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='statework',
            old_name='nombre',
            new_name='name',
        ),
    ]
