# Generated by Django 4.2.5 on 2023-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendientes por aprobación'), ('1', 'Aprobadas'), ('2', 'Rechazadas')], max_length=1),
        ),
    ]
