# Generated by Django 4.2.5 on 2023-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0002_alter_horaextra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='cod_4185',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4190',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4195',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4200',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4205',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4210',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4215',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4220',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4225',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4230',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4235',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4240',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4245',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4270',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_4275',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='cod_9054',
            field=models.FloatField(default=0.0),
        ),
    ]
