# Generated by Django 4.2.5 on 2024-02-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0007_contrato_unidades_territoriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='QProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('q_meta', models.PositiveIntegerField()),
                ('q_proceso', models.PositiveIntegerField()),
                ('q_ejecutada', models.PositiveIntegerField()),
                ('q_facturado', models.PositiveIntegerField()),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso')),
                ('unidad_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.unidadterritorial')),
            ],
        ),
        migrations.CreateModel(
            name='PProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('p_meta', models.PositiveIntegerField()),
                ('p_proceso', models.PositiveIntegerField()),
                ('p_ejecutada', models.PositiveIntegerField()),
                ('p_facturado', models.PositiveIntegerField()),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso')),
                ('unidad_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.unidadterritorial')),
            ],
        ),
    ]
