# Generated by Django 4.2.5 on 2024-01-24 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdlTqi',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('0', 'Trabajos en Tensión (ID)'), ('1', 'Trabajos en Tensión (PSTL)'), ('2', 'Trabajos sin Tensión (PDL)')], max_length=1)),
                ('descripcion', models.TextField()),
                ('estado_stweb', models.CharField(choices=[('0', 'Aprobado'), ('1', 'En ejecución')], max_length=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('circuito', models.CharField(max_length=255)),
                ('unidad_territorial', models.CharField()),
                ('unidad', models.CharField()),
                ('causal', models.CharField(choices=[('0', 'Emergencial'), ('1', 'Programado')], max_length=1)),
                ('pdl_asociado', models.CharField(max_length=15)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('contrato', models.CharField(max_length=25)),
                ('municipio', models.CharField()),
                ('vereda_localidad', models.CharField()),
                ('direccion', models.CharField()),
                ('estado_tqi', models.CharField(choices=[('0', 'SIN ASIGNACION'), ('1', 'PROGRAMADO INTERVENTORIA'), ('2', 'ASIGNADO PERSONAL PROPIO')], max_length=1)),
                ('criticidad_maniobra', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MetasTQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_territorial', models.CharField()),
                ('contrato', models.CharField()),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('cantidad_programada', models.PositiveIntegerField()),
                ('cantidad_ejecutada', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('responsable_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetasInspectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField()),
                ('anio', models.CharField()),
                ('mes', models.PositiveIntegerField()),
                ('cantidad_programada', models.PositiveIntegerField()),
                ('cantidad_ejecutada', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('responsable_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id_asignacion', models.CharField(default='N/A', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('cedula_inspector', models.CharField(max_length=11)),
                ('estado_stweb', models.CharField(choices=[('0', 'Aprobado'), ('1', 'En ejecución')], max_length=1)),
                ('cedula_responsable_asignacion', models.CharField(max_length=11)),
                ('fecha_asignacion', models.DateTimeField()),
                ('ejecutado', models.BooleanField()),
                ('pdl_tqi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspecciones_tqi.pdltqi')),
            ],
        ),
    ]
