# Generated by Django 4.2.5 on 2024-03-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManiobrasTqi',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('0', 'Trabajos en Tensión (ID)'), ('1', 'Trabajos en Tensión (PSTL)'), ('2', 'Trabajos sin Tensión (PDL)'), ('3', 'Verificación y prueba (VyP)'), ('4', 'Incidencia (Ticket)'), ('5', 'Trabajo en proximidad (PI)')], max_length=1)),
                ('descripcion', models.TextField()),
                ('estado_stweb', models.CharField(choices=[('0', 'Aprobado'), ('1', 'En ejecución')], max_length=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('causal', models.CharField(choices=[('0', 'Emergencial'), ('1', 'Programado')], max_length=1)),
                ('pdl_asociado', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_tqi', models.CharField(choices=[('0', 'SIN ASIGNACION'), ('1', 'PROGRAMADO INTERVENTORIA'), ('2', 'ASIGNADO PERSONAL PROPIO')], max_length=1)),
                ('criticidad_maniobra', models.CharField(blank=True, max_length=200, null=True)),
                ('cuadrilla_responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_cuadrilla_responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('inspeccion_ejecutada', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetasInspectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=200)),
                ('mes', models.PositiveIntegerField()),
                ('cantidad_meta', models.PositiveIntegerField()),
                ('cantidad_programada', models.PositiveIntegerField()),
                ('cantidad_ejecutada', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('responsable_actualizacion', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='MetasTQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('cantidad_meta', models.PositiveIntegerField()),
                ('cantidad_programada', models.PositiveIntegerField()),
                ('cantidad_ejecutada', models.PositiveIntegerField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('responsable_actualizacion', models.CharField(max_length=11)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
            ],
        ),
    ]
