# Generated by Django 4.2.5 on 2024-02-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdlTqi',
            new_name='ManiobrasTqi',
        ),
        migrations.RenameField(
            model_name='asignaciones',
            old_name='pdl_tqi',
            new_name='maniobra_tqi',
        ),
    ]
