# Generated by Django 4.2.5 on 2024-02-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0002_circuito_cantidad_trafos'),
        ('inspecciones_tqi', '0002_rename_pdltqi_maniobrastqi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maniobras',
            name='fecha_programacion',
        ),
        migrations.RemoveField(
            model_name='maniobrastqi',
            name='unidad',
        ),
        migrations.AddField(
            model_name='maniobrastqi',
            name='cuadrilla_responsable',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='maniobrastqi',
            name='subestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.subestacion'),
        ),
        migrations.AddField(
            model_name='maniobrastqi',
            name='telefono_cuadrilla_responsable',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='maniobrastqi',
            name='unidad_ejecutora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_unidad_ejecutora', to='static_data.unidadterritorial'),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.circuito'),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_contrato', to='static_data.contrato'),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_municipio', to='static_data.municipio'),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='pdl_asociado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='unidad_territorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_unidad_territorial', to='static_data.unidadterritorial'),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='vereda_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maniobra_vereda_localidad', to='static_data.vereda'),
        ),
    ]
