# Generated by Django 4.2.5 on 2024-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0003_alter_pdltqi_pdl_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasinspectores',
            name='inspector',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='metasinspectores',
            name='responsable_actualizacion',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='metastqi',
            name='responsable_actualizacion',
            field=models.CharField(max_length=11),
        ),
    ]
