# Generated by Django 4.2.5 on 2024-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0004_alter_metasinspectores_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasinspectores',
            name='cantidad_meta',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metastqi',
            name='cantidad_meta',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
