# Generated by Django 4.2.5 on 2024-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0004_alter_maniobrastqi_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maniobrastqi',
            name='tipo',
            field=models.CharField(choices=[('0', 'Trabajos en Tensión (ID)'), ('1', 'Trabajos en Tensión (PSTL)'), ('2', 'Trabajos sin Tensión (PDL)'), ('3', 'Verificación y prueba (VyP)'), ('4', 'Incidencia (Ticket)'), ('5', 'Trabajo en proximidad (PI)')], max_length=1),
        ),
    ]
