# Generated by Django 4.2.5 on 2024-02-14 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecciones_tqi', '0005_alter_maniobrastqi_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maniobrastqi',
            name='inspctor_asingado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Asignaciones',
        ),
    ]
