# Generated by Django 4.2.5 on 2024-02-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0006_maniobrastqi_inspctor_asingado_delete_asignaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maniobrastqi',
            old_name='inspctor_asingado',
            new_name='inspector_asingado',
        ),
    ]
