# Generated by Django 4.2.5 on 2024-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0006_maniobras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maniobras',
            name='fecha_actualizacion',
            field=models.DateTimeField(),
        ),
    ]
