# Generated by Django 4.2.5 on 2024-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0007_alter_maniobras_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maniobras',
            name='causal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='circuito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='co',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='firma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='localidad_municipio',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='nombre_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='pdl_asociado',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='telefono_reponsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='unidad_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='unidad_territorial',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='maniobras',
            name='unidad_territorial_std',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
