# Generated by Django 4.2.5 on 2024-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0007_rename_inspctor_asingado_maniobrastqi_inspector_asingado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maniobrastqi',
            name='cuadrilla_responsable',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='maniobrastqi',
            name='telefono_cuadrilla_responsable',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
