# Generated by Django 4.2.5 on 2024-02-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0008_alter_maniobrastqi_cuadrilla_responsable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maniobras',
        ),
    ]
