# Generated by Django 4.2.5 on 2024-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0009_delete_maniobras'),
    ]

    operations = [
        migrations.AddField(
            model_name='maniobrastqi',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maniobrastqi',
            name='mes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
