# Generated by Django 4.2.5 on 2024-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones_tqi', '0010_maniobrastqi_anio_maniobrastqi_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='maniobrastqi',
            name='inspeccion_ejecutada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
