# Generated by Django 4.2.5 on 2024-02-14 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0004_alter_contrato_nombre_alter_contrato_objeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecciones_tqi', '0011_maniobrastqi_inspeccion_ejecutada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metastqi',
            name='unidad_territorial',
        ),
        migrations.AlterField(
            model_name='metasinspectores',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metastqi',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato'),
        ),
    ]
