# Generated by Django 4.2.5 on 2024-04-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('objetive', models.CharField(blank=True, max_length=750, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('management_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrat_menegemer', to='location_management.territorialunit')),
                ('territorial_units', models.ManyToManyField(to='location_management.territorialunit')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTeam',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=25)),
                ('process_group', models.CharField(blank=True, choices=[('0', 'PROGRAMADO'), ('1', 'NO PROGRAMADO'), ('2', 'TELECONTROL')], max_length=1, null=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contracts_management.contrat')),
            ],
        ),
    ]
