# Generated by Django 4.2.5 on 2024-04-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C6Modules',
            new_name='C6Module',
        ),
    ]
