# Generated by Django 4.2.5 on 2024-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_management', '0001_initial'),
        ('users_management', '0003_rename_c6modules_c6module'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='process',
            field=models.ManyToManyField(blank=True, related_name='user_process', to='process_management.process'),
        ),
    ]
