# Generated by Django 4.2.5 on 2023-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0003_remove_municipio_unidad_territorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('codigo_prestacion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('codigo_elenco', models.CharField(max_length=8, unique=True)),
                ('texto_prestacion', models.TextField()),
                ('descripcion_prestacion', models.TextField()),
                ('alcance', models.CharField(max_length=5)),
                ('posicion', models.CharField(max_length=3)),
                ('factor_dispersion', models.CharField(max_length=4)),
                ('grupo_mercologico', models.CharField(choices=[(0, 'SLTR2600'), (1, 'LELE0501'), (2, 'LELE0600'), (3, 'LELE0502'), (4, 'LEII0900'), (5, 'FEGE0200'), (6, 'MELE0200'), (7, 'LELE0504'), (8, 'SRTS2200')], max_length=1)),
                ('precion_prestacion', models.FloatField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
            ],
        ),
    ]
