# Generated by Django 5.0.2 on 2024-02-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('codigo_prestacion', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('codigo_elenco', models.CharField(max_length=8)),
                ('texto_prestacion', models.TextField()),
                ('alcance', models.TextField()),
                ('unidad_medida', models.CharField(blank=True, max_length=5, null=True)),
                ('posicion', models.CharField(max_length=3)),
                ('factor_dispersion', models.CharField(max_length=4)),
                ('grupo_mercologico', models.CharField(choices=[('0', 'SLTR2600'), ('1', 'LELE0501'), ('2', 'LELE0600'), ('3', 'LELE0502'), ('4', 'LEII0900'), ('5', 'FEGE0200'), ('6', 'MELE0200'), ('7', 'LELE0504'), ('8', 'SRTS2200')], max_length=1)),
                ('precio_prestacion', models.FloatField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
            ],
        ),
    ]
