# Generated by Django 4.2.5 on 2023-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestaciones', '0002_remove_prestacion_descripcion_prestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacion',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
