# Generated by Django 4.2.5 on 2023-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestaciones', '0003_prestacion_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='codigo_elenco',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='grupo_mercologico',
            field=models.CharField(choices=[('0', 'SLTR2600'), ('1', 'LELE0501'), ('2', 'LELE0600'), ('3', 'LELE0502'), ('4', 'LEII0900'), ('5', 'FEGE0200'), ('6', 'MELE0200'), ('7', 'LELE0504'), ('8', 'SRTS2200')], max_length=1),
        ),
    ]
