#!/bin/bash

NAME="control6"                                  # Name of the application
DJANGODIR=/webapps/back-c6/C6_BackEnd_Monolitico/control6             # Django project directory
SOCKFILE=/webapps/back-c6/run/gunicorn.sock  # we will communicte using this unix socket
USER=root                                        # the user to run as
GROUP=root                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=control6.settings.prod             # which settings file should Django use
DJANGO_WSGI_MODULE=control6.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Detener los procesos Celery existentes si hay alguno
pkill -f 'celery -A control6'


# Iniciar celery
celery -A control6 worker --loglevel INFO --logfile=../../logs/worker.log &
celery -A control6 beat -l info --logfile=../../logs/beat.log &

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-