# Generated by Django 4.2.5 on 2024-03-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_control', models.CharField(default='N/A', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pms_quotation', models.CharField(blank=True, max_length=50, null=True)),
                ('pms_need', models.CharField(blank=True, max_length=50, null=True)),
                ('caso_radicado', models.CharField(blank=True, max_length=180, null=True)),
                ('alcance', models.TextField()),
                ('priorizacion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=180)),
                ('equipo_referencia', models.CharField(blank=True, max_length=25, null=True)),
                ('carga_solicitada', models.CharField(blank=True, max_length=25, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('estado_mare', models.CharField(blank=True, choices=[('0', 'ABIERTO'), ('1', 'YA NO ESTÁ PRESENTE'), ('2', 'ANULADO PLAN DE INVERSIÓN'), ('3', 'EJECUTADO')], max_length=1, null=True)),
                ('estado_pms', models.CharField(blank=True, choices=[('0', 'Por Valorizar'), ('1', 'Enviado a territorio'), ('2', 'Valorizado'), ('3', 'ODM Asignadas'), ('4', 'PDL Programado'), ('5', 'Trabajos finalizados'), ('6', 'Negar solicitud')], max_length=1, null=True)),
                ('anio_meta', models.PositiveIntegerField(blank=True, null=True)),
                ('mes_meta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.circuito')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
                ('estructura_presupuestal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.estructurapresupuestal')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.municipio')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso')),
                ('ruta_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.rutaproceso')),
                ('subestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.subestacion')),
                ('unidad_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.unidadterritorial')),
                ('vereda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.vereda')),
            ],
        ),
        migrations.CreateModel(
            name='SoportesIniciales',
            fields=[
                ('id_soporte', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='soportes_iniciales')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.trabajo')),
            ],
        ),
    ]
