# Generated by Django 4.2.5 on 2024-02-12 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lcl',
            fields=[
                ('lcl', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_lcl', models.CharField(choices=[('0', 'LIBERACION OPERATIVA'), ('1', 'ENVIAR A SCM'), ('2', 'EN SCM'), ('3', 'FACTURADA'), ('4', 'ANULADA')], max_length=1)),
                ('indicador_impuesto', models.CharField(choices=[('WC', 'INVERSION'), ('WK', 'WK - GASTO'), ('WI', 'WI - GASTO')], max_length=2)),
                ('valor_mano_obra', models.FloatField()),
                ('valor_materiales', models.FloatField()),
                ('texto_scm', models.TextField()),
                ('alcance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id_nodo', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('nodo', models.CharField(max_length=20)),
                ('latitud_inicial', models.CharField(max_length=11)),
                ('longitud_inicial', models.CharField(max_length=11)),
                ('latitud_final', models.CharField(blank=True, max_length=11, null=True)),
                ('longitud_final', models.CharField(blank=True, max_length=11, null=True)),
                ('punto_fisico_final', models.CharField(blank=True, max_length=10, null=True)),
                ('punto_fisico_inicial', models.CharField(blank=True, max_length=10, null=True)),
                ('norma_codensa_punto_inicial', models.CharField(blank=True, max_length=10, null=True)),
                ('norma_codensa_punto_final', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_nodo', models.CharField(blank=True, choices=[('0', 'Nodo red'), ('1', 'Tramo red'), ('2', 'Equipo'), ('3', 'Transformador'), ('4', 'Cámara subterránea'), ('5', 'Tramo canalización'), ('6', 'Ramming'), ('7', 'Cercha')], max_length=1, null=True)),
                ('tipo_instalacion', models.CharField(blank=True, choices=[('0', 'Aéreo'), ('1', 'Subterráneo')], max_length=1, null=True)),
                ('tramo', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_seccion', models.CharField(blank=True, max_length=125, null=True)),
                ('cod_defecto', models.CharField(blank=True, max_length=250, null=True)),
                ('valor_mano_obra', models.FloatField(blank=True, null=True)),
                ('valor_materiales', models.FloatField(blank=True, null=True)),
                ('id_mare', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_tension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.niveltension')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_control', models.CharField(default='N/A', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pms_quotation', models.CharField(blank=True, max_length=50, null=True)),
                ('pms_need', models.CharField(blank=True, max_length=50, null=True)),
                ('caso_radicado', models.CharField(blank=True, max_length=50, null=True)),
                ('alcance', models.TextField()),
                ('priorizacion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=160)),
                ('equipo_referencia', models.CharField(blank=True, max_length=25, null=True)),
                ('carga_solicitada', models.CharField(blank=True, max_length=25, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('estado_mare', models.CharField(blank=True, choices=[('0', 'ABIERTO'), ('1', 'YA NO ESTÁ PRESENTE'), ('2', 'ANULADO PLAN DE INVERSIÓN'), ('3', 'EJECUTADO')], max_length=1, null=True)),
                ('estado_pms', models.CharField(blank=True, choices=[('0', 'Por Valorizar'), ('1', 'Enviado a territorio'), ('2', 'Valorizado'), ('3', 'ODM Asignadas'), ('4', 'PDL Programado'), ('5', 'Trabajos finalizados'), ('6', 'Negar solicitud')], max_length=1, null=True)),
                ('anio_meta', models.PositiveIntegerField(blank=True, null=True)),
                ('mes_meta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.circuito')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
                ('estructura_presupuestal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.estructurapresupuestal')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.municipio')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso')),
                ('ruta_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.rutaproceso')),
                ('subestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.subestacion')),
                ('unidad_territorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.unidadterritorial')),
                ('vereda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.vereda')),
            ],
        ),
        migrations.CreateModel(
            name='Valorizacion',
            fields=[
                ('id_valorizacion', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('monto_mano_obra', models.FloatField()),
                ('monto_materiales', models.FloatField()),
                ('fecha_valorizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('0', 'Revisión'), ('1', 'Rechazado'), ('2', 'Aprobado'), ('3', 'Aprobado con modificación'), ('4', 'Anulado')], max_length=1)),
                ('presupuesto', models.FileField(blank=True, null=True, upload_to='presupuesto')),
                ('nivel_tension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.niveltension')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trazabilidad', models.DateTimeField()),
                ('comentario_trazabilidad', models.TextField()),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidad_trabajo', to='work_management.trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidad_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoportesIniciales',
            fields=[
                ('id_soporte', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='soportes_iniciales')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id_programcion', models.CharField(default='N/A', editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('fecha_ejecucion', models.DateField()),
                ('alcance', models.TextField()),
                ('estado', models.CharField(choices=[('0', 'Sin maniobra'), ('1', 'Con maniobra no aprobada'), ('2', 'Con maniobra aprobada'), ('3', 'Ejecutada'), ('4', 'Ejecutada parcialmente'), ('5', 'Cancelada')], max_length=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ticket', models.BooleanField(blank=True, null=True)),
                ('pdl', models.BooleanField(blank=True, null=True)),
                ('pi', models.BooleanField(blank=True, null=True)),
                ('pstl', models.BooleanField(blank=True, null=True)),
                ('vyp', models.BooleanField(blank=True, null=True)),
                ('planeacion_segura', models.FileField(blank=True, null=True, upload_to='programaciones')),
                ('cuadrillas', models.ManyToManyField(to='static_data.cuadrilla')),
                ('lcls', models.ManyToManyField(to='work_management.lcl')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_management.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Odm',
            fields=[
                ('odm', models.BigIntegerField(primary_key=True, serialize=False)),
                ('agp', models.BigIntegerField()),
                ('protocolo', models.BigIntegerField()),
                ('solicitud', models.BigIntegerField()),
                ('valorizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.valorizacion')),
            ],
        ),
        migrations.CreateModel(
            name='NodoMDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo_mdo', models.CharField(choices=[('0', 'Retiro'), ('1', 'Instlación'), ('2', 'Traslado'), ('3', 'Otro')], max_length=1)),
                ('codigo_mdo', models.CharField(max_length=8)),
                ('cantidad_replanteada', models.FloatField(blank=True, null=True)),
                ('cantidad_ejecutada', models.FloatField(blank=True, null=True)),
                ('cantidad_facturada', models.FloatField(blank=True, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='NodoMAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo_mat', models.CharField(choices=[('0', 'Instalación nuevo'), ('1', 'Instalación reutilizable'), ('2', 'Retiro chatarra'), ('3', 'Retirado reutilizable'), ('4', 'Material de aportacion'), ('5', 'Hurto'), ('6', 'No se pudo sacar el material')], max_length=1)),
                ('codigo_mat', models.CharField(max_length=8)),
                ('cantidad_replanteada', models.FloatField(blank=True, null=True)),
                ('cantidad_ejecutada', models.FloatField(blank=True, null=True)),
                ('cantidad_facturada', models.FloatField(blank=True, null=True)),
                ('aportacion', models.BooleanField(blank=True, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.nodo')),
            ],
        ),
        migrations.AddField(
            model_name='nodo',
            name='valorizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.valorizacion'),
        ),
        migrations.CreateModel(
            name='Maniobra',
            fields=[
                ('maniobra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo_maniobra', models.CharField(choices=[('0', 'PDL'), ('1', 'PI'), ('2', 'PSTL')], max_length=1)),
                ('alcance', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_maniobra', models.CharField(choices=[('0', 'PENDIENTE POR APROBAR'), ('1', 'APROBADO'), ('2', 'PARA CORREGIR'), ('3', 'EJECUTADO')], max_length=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('programaciones', models.ManyToManyField(to='work_management.programacion')),
            ],
        ),
        migrations.CreateModel(
            name='Libreto',
            fields=[
                ('id_libreto', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('numero_libreto', models.CharField(max_length=3)),
                ('valor_mod', models.FloatField()),
                ('valor_mat', models.FloatField()),
                ('observacion', models.TextField()),
                ('planillas_conciliacion', models.FileField(blank=True, null=True, upload_to='planillas-conciliacion')),
                ('planillas_firmadas', models.FileField(blank=True, null=True, upload_to='planillas-firmadas')),
                ('estado_libreto', models.CharField(choices=[('0', 'PLANILLAS - CONCILIACIÓN'), ('1', 'PLANILLAS - RECHAZADAS'), ('2', 'PLANILLAS - FIRMADAS'), ('3', 'LIBRETO CARGADO EN SCM'), ('4', 'LIBRETO DEVULETO'), ('5', 'LIBRETO LIBERADO TECNICAMENTE'), ('6', 'LIBRETO LIBERADO CONTABLEMENTE'), ('7', 'LIBRETO CONFORMADO')], max_length=1)),
                ('es_ultimo_libreto', models.BooleanField()),
                ('lcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='work_management.lcl')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.programacion')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='lcl',
            name='odms',
            field=models.ManyToManyField(to='work_management.odm'),
        ),
        migrations.AddField(
            model_name='lcl',
            name='responsable_scm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NodoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programado', models.CharField(choices=[('0', 'Parcial'), ('1', 'Completo'), ('2', 'Cancelado')], max_length=1)),
                ('ejecutado', models.CharField(blank=True, choices=[('0', 'Parcial'), ('1', 'Completo'), ('2', 'Cancelado')], max_length=1, null=True)),
                ('facturado', models.BooleanField(blank=True, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.nodo')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.programacion')),
            ],
            options={
                'unique_together': {('nodo', 'programacion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='nodo',
            unique_together={('valorizacion', 'nodo')},
        ),
        migrations.CreateModel(
            name='EtlBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion_retiro', models.CharField(choices=[('0', 'Retiro'), ('1', 'Instlación'), ('2', 'Traslado'), ('3', 'Otro')], max_length=1)),
                ('codigo', models.CharField(max_length=8)),
                ('cantidad', models.FloatField()),
                ('mat_mdo', models.CharField(choices=[('0', 'Material'), ('1', 'Mano de obra')], max_length=1)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('aportacion', models.BooleanField()),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.nodo')),
            ],
            options={
                'unique_together': {('nodo', 'codigo')},
            },
        ),
    ]
