# Generated by Django 4.2.5 on 2023-10-02 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lcl',
            fields=[
                ('numero_lcl', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_lcl', models.CharField(choices=[('0', 'LIBERACION OPERATIVA'), ('1', 'ENVIAR A SCM'), ('2', 'EN SCM'), ('3', 'FACTURADA')], max_length=1)),
                ('indicador_impuesto', models.CharField(choices=[('WC', 'INVERSION'), ('WK', 'WK - GASTO'), ('WI', 'WI - GASTO')], max_length=2)),
                ('valor_mano_obra', models.FloatField()),
                ('valor_materiales', models.FloatField()),
                ('responsable_scm', models.CharField(max_length=50)),
                ('texto_scm', models.CharField(max_length=250)),
                ('alcance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Odm',
            fields=[
                ('odm', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valorizacion', models.CharField(max_length=23)),
                ('agp', models.BigIntegerField()),
                ('protocolo', models.BigIntegerField()),
                ('solicitud', models.BigIntegerField()),
                ('tiene_lcl', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_control', models.CharField(default='N/A', editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pms_quotation', models.CharField(max_length=50)),
                ('pms_need', models.CharField(max_length=50)),
                ('proceso', models.CharField(max_length=8)),
                ('caso_radicado', models.CharField(max_length=50)),
                ('estado_trabajo', models.CharField(max_length=8)),
                ('alcance', models.TextField()),
                ('estructura_presupuestal', models.CharField(max_length=25)),
                ('priorizacion', models.DateField()),
                ('unidad_territorial', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=6)),
                ('vereda', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=120)),
                ('subestacion', models.CharField(max_length=2)),
                ('circuito', models.CharField(max_length=8)),
                ('contrato', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Valorizacion',
            fields=[
                ('id_valorizacion', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('trabajo', models.CharField(max_length=20)),
                ('monto_mano_obra', models.FloatField()),
                ('monto_materiales', models.FloatField()),
                ('estado', models.CharField(choices=[('0', 'Revisión'), ('1', 'Rechazado'), ('2', 'Aprobado'), ('3', 'Anulado')], max_length=1)),
                ('nivel_tension', models.CharField(max_length=8)),
                ('presupuesto', models.FileField(blank=True, null=True, upload_to='presupuesto')),
                ('estado_trabajo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trazabilidad', models.DateField()),
                ('comentario_trazabilidad', models.TextField()),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidad_trabajo', to='work_management.trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trazabilidad_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id_programcion', models.CharField(default='N/A', editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('fecha_ejecucion', models.DateField()),
                ('alcance', models.TextField()),
                ('estado', models.CharField(choices=[('0', 'Sin maniobra'), ('1', 'Con maniobra no aprobada'), ('2', 'Con maniobra aprobada')], max_length=1)),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.cuadrilla')),
                ('lcl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.lcl')),
            ],
        ),
        migrations.CreateModel(
            name='Maniobra',
            fields=[
                ('mabiobra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo_maniobra', models.CharField(choices=[('0', 'PDL'), ('1', 'PI'), ('2', 'PSTL')], max_length=1)),
                ('alcance', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_maniobra', models.CharField(choices=[('0', 'PENDIENTE POR APROBAR'), ('1', 'APROBADO')], max_length=1)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.programacion')),
            ],
        ),
        migrations.AddField(
            model_name='lcl',
            name='odms',
            field=models.ManyToManyField(to='work_management.odm'),
        ),
        migrations.CreateModel(
            name='Ejecutado',
            fields=[
                ('id_ejecucutado', models.CharField(default='N/A', editable=False, max_length=23, primary_key=True, serialize=False, unique=True)),
                ('monto_mano_obra', models.FloatField()),
                ('monto_materiales', models.FloatField()),
                ('estado', models.CharField(choices=[('0', 'Soportes EECC'), ('1', 'Soportes Enel'), ('2', 'Planillas firmadas'), ('3', 'Rechazdo')], max_length=1)),
                ('soporte', models.FileField(upload_to=None)),
                ('maniobras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_management.maniobra')),
            ],
        ),
    ]
