# Generated by Django 4.2.5 on 2023-10-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_data', '0002_initial'),
        ('work_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='caso_radicado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='direccion',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estructura_presupuestal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.estructurapresupuestal'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='pms_need',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='pms_quotation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='priorizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
