# Generated by Django 4.2.5 on 2023-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0002_alter_trabajo_caso_radicado_alter_trabajo_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='fecha_trazabilidad',
            field=models.DateTimeField(),
        ),
    ]
