# Generated by Django 4.2.5 on 2024-02-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero_contrato', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('objeto', models.CharField(max_length=250)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTrabajo',
            fields=[
                ('id_estado', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraPresupuestal',
            fields=[
                ('id_estructura_pptal', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(max_length=20)),
                ('anio', models.CharField(max_length=4)),
                ('macrocategoria', models.CharField(max_length=15)),
                ('ir', models.CharField(max_length=2)),
                ('proyecto', models.CharField(max_length=50)),
                ('indicador_impuesto', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloBandeja',
            fields=[
                ('id_modulo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_municipio', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cft', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NivelTension',
            fields=[
                ('nivel', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('rango', models.CharField(max_length=80)),
                ('valor_nominal_v', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('codigo_proceso', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=350)),
                ('ejecucion_ticket', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstalacion',
            fields=[
                ('id_tipo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTerritorial',
            fields=[
                ('numero', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('codigo_vereda', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_vereda', models.CharField(max_length=60)),
                ('factor_dispersion', models.CharField(max_length=2)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Subestacion',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('nivel_tension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nt', to='static_data.niveltension')),
                ('unidades_territoriales', models.ManyToManyField(to='static_data.unidadterritorial')),
            ],
        ),
        migrations.CreateModel(
            name='RutaProceso',
            fields=[
                ('codigo_ruta', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('paso', models.CharField(max_length=2)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.estadotrabajo')),
                ('modulos', models.ManyToManyField(to='static_data.modulobandeja')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='unidad_territorial',
            field=models.ManyToManyField(to='static_data.unidadterritorial'),
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('codigo_cuadrilla', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_cuadrilla', models.CharField(max_length=25)),
                ('grupo_proceso', models.CharField(blank=True, choices=[('0', 'PROGRAMADO'), ('1', 'NO PROGRAMADO'), ('2', 'TELECONTROL')], max_length=1, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='static_data.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato_gestoria', to='static_data.unidadterritorial'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='unidades_territoriales',
            field=models.ManyToManyField(related_name='contratos_operacion_territorial', to='static_data.unidadterritorial'),
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('codigo_circuito', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ubicacion_tecnica', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('longitud_aerea_mt', models.PositiveIntegerField()),
                ('logitud_subterranea_mt', models.PositiveIntegerField()),
                ('cantidad_clientes', models.PositiveIntegerField()),
                ('subestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_data.subestacion')),
                ('tesniones_nominales', models.ManyToManyField(to='static_data.niveltension')),
            ],
        ),
    ]
