# Generated by Django 4.2.5 on 2023-10-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadterritorial',
            name='jefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subestacion',
            name='nivel_tension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nt', to='static_data.niveltension'),
        ),
        migrations.AddField(
            model_name='rutaproceso',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.estadotrabajo'),
        ),
        migrations.AddField(
            model_name='rutaproceso',
            name='modulos',
            field=models.ManyToManyField(to='static_data.modulobandeja'),
        ),
        migrations.AddField(
            model_name='rutaproceso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.proceso'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='unidad_territorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='static_data.unidadterritorial'),
        ),
        migrations.AddField(
            model_name='circuito',
            name='subestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='static_data.subestacion'),
        ),
        migrations.AddField(
            model_name='circuito',
            name='tesniones_nominales',
            field=models.ManyToManyField(to='static_data.niveltension'),
        ),
    ]
